### ISSUE TITLE
draw_boxes is not defined

### ISSUE THREAD

**Issue by andreazuna89** [RizwanMunawar/yolov8-object-tracking#10]
Hi,
I am running python yolo\v8\detect\detect_and_trk.py model=yolov8m.pt source=0 show=True but I get the following error:

File "yolo/v8/detect/detect_and_trk.py", line 115, in write_results
    draw_boxes(im0, bbox_xyxy, identities, categories, self.model.names)
NameError: name 'draw_boxes' is not defined

Set the environment variable HYDRA_FULL_ERROR=1 for a complete stack trace.
terminate called without an active exception

Can you help me?
Thanks
Andrea

**Comment by RizwanMunawar** [comment]
@andreazuna89! Your issue has been fixed now! Please clone the latest code and use it Thanks
