### ISSUE TITLE
AttributeError: 'DetectionPredictor' object has no attribute 'all_outputs'

### ISSUE THREAD

**Issue by hongu0603** [RizwanMunawar/yolov8-object-tracking#6]
![螢幕擷取畫面 2023-01-18 171154](https://user-images.githubusercontent.com/80024143/213130658-5564600d-63c9-4577-a389-b085185a9611.png)

**Comment by RizwanMunawar** [comment]
@hongu0603! You are using Windows 8? Apart from that, can you provide the source file's complete system path, instead of the absolute file path?

**Comment by hongu0603** [comment]
@RizwanMunawar I am using Window10 !  I use file's complete system path but get the same result
![image](https://user-images.githubusercontent.com/80024143/213333327-2fab3e64-753a-4a2f-88cd-1533bbdc90b5.png)

**Comment by hongu0603** [comment]
I solve this problem by declare all_outputs as local variable
![image](https://user-images.githubusercontent.com/80024143/213335287-0fa040cd-5e6e-41df-9843-d54647a53fca.png)

**Comment by RizwanMunawar** [comment]
@hongu0603! Nice work, please test it, and If you think it's working fine you can send a pull request! :)
