### ISSUE TITLE
ImportError: cannot import name 'DEFAULT_CONFIG' from 'ultralytics.yolo.utils

### ISSUE THREAD

**Issue by BoscoShin** [RizwanMunawar/yolov8-object-tracking#8]
i have problem to tracking object.

i followed tutorial in document, so i ran the dete~trk.py. but i got the import error.

how can i fix it?

![image](https://user-images.githubusercontent.com/75238411/215043227-98afe964-383b-4ff2-bdc3-079d5ee4567a.png)

Best,
BoscoShin

**Comment by RizwanMunawar** [comment]
@BoscoShin! Did you run the code on google colab?

**Comment by BoscoShin** [comment]
@RizwanMunawar  no, i didnt. i run the code on jupyter notebook.

do i run the code on google colab?

**Comment by RizwanMunawar** [comment]
@BoscoShin! The issue I know and already resolved. In some hrs, I will update the code and will also add ready-to-use Colab.

I am sure, it will possibly resolve your issue.

**Comment by BoscoShin** [comment]
@RizwanMunawar! Thanks you. :)

**Comment by RizwanMunawar** [comment]
@BoscoShin! This issue is related to the Ultralytics package version. You will need to Install ultralytics package 8.0.0. You can use mentioned command below to install it.

```
pip install ultralytics==8.0.0
```

**Comment by BoscoShin** [comment]
@RizwanMunawar Thanks you. i will try it.

**Comment by utkarshtambe10** [comment]
> @BoscoShin! Did you run the code on google colab?

I am running on Google colab so how to resolve this issue?
Thanks & Reagrds,
Utkarsh Tambe

**Comment by simba404** [comment]
> @BoscoShin! This issue is related to the Ultralytics package version. You will need to Install ultralytics package 8.0.0. You can use mentioned command below to install it.
> 
> ```
> pip install ultralytics==8.0.0
> ```

it does solve the problem above , but it will cause a new problem. which is ImportError: cannot import name 'DEFAULT_CONFIG' from 'ultralytics.yolo.utils'

**Comment by rushikesh2842** [comment]
@RizwanMunawar i installed ultralytics version 8.0.0 but on doing that, a dependency conflict arises as the yolo package requires ultralyytics verison>=8.0.100. How to resolve this issue??
