### ISSUE TITLE
Error while using tracker on custom trained yolov8 segmentation model 

### ISSUE THREAD

**Issue by andreazuna89** [RizwanMunawar/yolov8-object-tracking#9]
Hi, 
Thanks for the great work. I was playing with your code and I was using a yolov8 segmentation model trained on a custom dataset. I get the following error:

YOLOv8x-seg summary: 295 layers, 71729323 parameters, 0 gradients, 343.7 GFLOPs
1/1: 0...  Success (inf frames 640x480 at 30.00 FPS)

Traceback (most recent call last):
  File "track.py", line 367, in <module>
    main(opt)
  File "track.py", line 362, in main
    run(**vars(opt))
  File "/home/azunino/anaconda3/envs/tracking/lib/python3.7/site-packages/torch/autograd/grad_mode.py", line 27, in decorate_context
    return func(*args, **kwargs)
  File "track.py", line 220, in run
    s += f"{n} {names[int(c)]}{'s' * (n > 1)}, "  # add to string
KeyError: 12
Aborted (core dumped)

Can you help me here? That error comes only when I use a model pretrained on custom data.

Thanks
Andrea

**Comment by RizwanMunawar** [comment]
@andreazuna89! Tracking for object segmentation is not supported!
